adjective = input("Enter an adjective: ")
verb = input("Enter a verb: ")
print("I love programming because it is " + adjective + " and I love to" + verb + " wth it.")
print("I love prog because it is {} ".format(adjective + "."))
print(f"I love you because you are {adjective}" + ".")
